version: '2'
services:
    lb:
        image: dockercloud/haproxy
        ports:
          - 80:80
        links:
          - blogapp
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    blogapp:
        build: .
        image: blogapp:${COMMIT}
        links:
            - blogdb:blogdb
        ports:
            - "8080"
    blogdb:
        image: postgres
        expose:
         - 5432
        environment:
          POSTGRES_PASSWORD: mysecretpassword